import test from 'node:test'
import assert from 'node:assert/strict'
import { createPrivateKey, createPublicKey } from 'crypto'
import { createEnvFile, createStackConfiguration, createTestEnvFile } from '../server.js'

function getEnvValue(content, name) {
    return content.match(new RegExp("^" + name + "=(.*)$", "m"))[1]
}

test("generates matching values for selected services", () => {
    const stackConfiguration = createStackConfiguration([
        { repo: "authservice", branch: "main" },
        { repo: "emailservice", branch: "main" },
        { repo: "fileservice", branch: "main" },
        { repo: "vaultservice", branch: "main" },
        { repo: "testservice", branch: "main" }
    ])
    const authEnv = createEnvFile("AUTHSERVICE_INTEGRATION=true\nFILESERVICE_INTEGRATION=true\nEMAILSERVICE_INTEGRATION=true\nVAULTSERVICE_INTEGRATION=true\nSERVICE_SECRET_FILE=change-me\nJWT_PRIVATE_KEY=change-me\nJWT_PUBLIC_KEY=change-me\nPOSTGRES_USER=change-me\nPOSTGRES_PASSWORD=change-me\nENCRYPTION_KEY=change-me", "authservice", stackConfiguration)
    const fileEnv = createEnvFile("AUTHSERVICE_INTEGRATION=true\nTELEMETRYSERVICE_INTEGRATION=true\nSERVICE_SECRET_FILE=change-me\nJWT_PUBLIC_KEY=change-me\nPOSTGRES_USER=change-me\nPOSTGRES_PASSWORD=change-me\nENCRYPTION_KEY=change-me", "fileservice", stackConfiguration)
    const testEnv = createEnvFile("EMAILSERVICE_INTEGRATION=true\nSERVICE_SECRET_TEST=change-me\nINITIAL_SUPER_CREDENTIALS_DIRECTORY=change-me\nINITIAL_SUPER_CREDENTIALS_FILE=change-me", "testservice", stackConfiguration)
    const privateKey = createPrivateKey({
        key: Buffer.from(getEnvValue(authEnv, "JWT_PRIVATE_KEY"), "base64"),
        format: "der",
        type: "pkcs8"
    })
    const publicKey = createPublicKey(privateKey).export({ type: "spki", format: "der" }).toString("base64")

    assert.match(authEnv, /^# Generated by MSINIT\. Do not commit this file\.$/m)
    assert.equal(getEnvValue(authEnv, "FILESERVICE_INTEGRATION"), "true")
    assert.equal(getEnvValue(fileEnv, "AUTHSERVICE_INTEGRATION"), "true")
    assert.equal(getEnvValue(fileEnv, "TELEMETRYSERVICE_INTEGRATION"), "false")
    assert.equal(getEnvValue(authEnv, "SERVICE_SECRET_FILE"), getEnvValue(fileEnv, "SERVICE_SECRET_FILE"))
    assert.equal(publicKey, getEnvValue(fileEnv, "JWT_PUBLIC_KEY"))
    assert.notEqual(getEnvValue(authEnv, "POSTGRES_PASSWORD"), getEnvValue(fileEnv, "POSTGRES_PASSWORD"))
    assert.match(getEnvValue(authEnv, "ENCRYPTION_KEY"), /^[A-F0-9]{32}$/)
    assert.equal(getEnvValue(testEnv, "SERVICE_SECRET_EMAIL"), stackConfiguration.serviceSecrets.email)
    assert.equal(getEnvValue(testEnv, "INITIAL_SUPER_CREDENTIALS_DIRECTORY"), "../authservice-main/bootstrap-credentials")
    assert.equal(getEnvValue(testEnv, "INITIAL_SUPER_CREDENTIALS_FILE"), "../authservice-main/bootstrap-credentials/initial-super-user.txt")
})

test("disables absent integrations", () => {
    const stackConfiguration = createStackConfiguration([
        { repo: "fileservice", branch: "main" }
    ])
    const fileEnv = createEnvFile("AUTHSERVICE_INTEGRATION=true\nTELEMETRYSERVICE_INTEGRATION=true\nJWT_PUBLIC_KEY=change-me\nSERVICE_SECRET_FILE=change-me", "fileservice", stackConfiguration)

    assert.equal(getEnvValue(fileEnv, "AUTHSERVICE_INTEGRATION"), "false")
    assert.equal(getEnvValue(fileEnv, "TELEMETRYSERVICE_INTEGRATION"), "false")
    assert.notEqual(getEnvValue(fileEnv, "JWT_PUBLIC_KEY"), "change-me")
    assert.notEqual(getEnvValue(fileEnv, "SERVICE_SECRET_FILE"), "change-me")
})

test("adds the selected CICD repository once", () => {
    const stackConfiguration = createStackConfiguration([
        { repo: "authservice", branch: "develop" },
        { repo: "jenkinsservice", branch: "develop" }
    ], "jenkins")

    assert.equal(stackConfiguration.repositories.filter(repository => repository.repo === "jenkinsservice").length, 1)
})

test("generates test rate limits", () => {
    const stackConfiguration = createStackConfiguration([
        { repo: "authservice", branch: "main" },
        { repo: "gatewayservice", branch: "main" },
        { repo: "testservice", branch: "main" }
    ])
    const authEnv = createTestEnvFile("INVITE_ONLY=false\nCOOKIE_SECURE=true\nLOGIN_RATE_LIMIT_MAX_REQUESTS=10\nREGISTER_RATE_LIMIT_MAX_REQUESTS=2\nPASSWORD_RESET_RATE_LIMIT_MAX_REQUESTS=3\nSERVICE_ACCOUNT_RATE_LIMIT_MAX_REQUESTS=30", "authservice", stackConfiguration)
    const gatewayEnv = createTestEnvFile("AUTH_GATEWAY_RATE_LIMIT_REPLENISH_RATE=5\nAUTH_GATEWAY_RATE_LIMIT_BURST_CAPACITY=60", "gatewayservice", stackConfiguration)

    assert.equal(getEnvValue(authEnv, "INVITE_ONLY"), "true")
    assert.equal(getEnvValue(authEnv, "COOKIE_SECURE"), "false")
    assert.equal(getEnvValue(authEnv, "REGISTER_RATE_LIMIT_MAX_REQUESTS"), "1000")
    assert.equal(getEnvValue(gatewayEnv, "AUTH_GATEWAY_RATE_LIMIT_REPLENISH_RATE"), "1000")
    assert.equal(getEnvValue(gatewayEnv, "AUTH_GATEWAY_RATE_LIMIT_BURST_CAPACITY"), "1000")
})
