services:
  msinit-backend-service:
    build: .
    networks:
      - "msinit-network"
    ports:
      - "3000:3000"
    container_name: msinit-backend-service
networks:
  msinit-network:
    external: true