services:
  msinit-backend:
    build: .
    networks:
      - "msinit-network"
      - "shared-network"
    ports:
      - "3000:3000"
    container_name: msinit-backend
networks:
  msinit-network:
    external: true
  shared-network:
    external: true
