# Application name
spring.application.name=${SPRING_APPLICATION_NAME:gatewayservice}

# Server host domains
hosts=${HOSTS:main=localhost:8080}

# Server port - Set to 8443 for HTTPS traffic
server.port=${SERVER_PORT:8080}

service.jenkins.url=${JENKINS_SERVICE_URL:http://jenkins-service:8080}
jenkinsservice.integration=${JENKINSSERVICE_INTEGRATION}
service.auth.url=${AUTH_SERVICE_URL:http://auth-service:6001}
authservice.integration=${AUTHSERVICE_INTEGRATION}
service.email.url=${EMAIL_SERVICE_URL:http://email-service:6005}
emailservice.integration=${EMAILSERVICE_INTEGRATION}
service.file.url=${FILE_SERVICE_URL:http://file-service:6010}
fileservice.integration=${FILESERVICE_INTEGRATION}
service.vault.url=${VAULT_SERVICE_URL:http://vault-service:6020}
vaultservice.integration=${VAULTSERVICE_INTEGRATION}
service.telemetry.url=${TELEMETRY_SERVICE_URL:http://telemetry-service:6050}
telemetryservice.integration=${TELEMETRYSERVICE_INTEGRATION}
service.react.url=${REACT_SERVICE_URL:http://react-service}
reactservice.integration=${REACTSERVICE_INTEGRATION}

# CORS origins
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:6080}

# HTTPS certificate settings
#server.ssl.enabled=${SERVER_SSL_ENABLED:true}
#server.ssl.key-store=${SERVER_SSL_KEY_STORE:file:/gatewayservice/certs/keystore.p12}
#server.ssl.key-store-password=${SERVER_SSL_KEY_STORE_PASSWORD:changeit}
#server.ssl.key-store-type=${SERVER_SSL_KEY_STORE_TYPE:PKCS12}

# Redis rate-limit config
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.connect-timeout=${REDIS_CONNECT_TIMEOUT}
spring.data.redis.timeout=${REDIS_TIMEOUT}
rate-limit.auth.replenish-rate=${AUTH_GATEWAY_RATE_LIMIT_REPLENISH_RATE}
rate-limit.auth.burst-capacity=${AUTH_GATEWAY_RATE_LIMIT_BURST_CAPACITY}
