spring.application.name=loggerservice
server.port=${SERVER_PORT}
opensearch.host=${OPENSEARCH_HOST:localhost}
opensearch.port=${OPENSEARCH_PORT:9200}
opensearch.username=${OPENSEARCH_USERNAME:admin}
opensearch.password=${OPENSEARCH_PASSWORD:}
opensearch.ssl.verification-mode=${OPENSEARCH_SSL_VERIFICATIONMODE:full}
dashboards.host=${DASHBOARDS_HOST:dashboards}
dashboards.port=${DASHBOARDS_PORT:5601}
service.http.connect.timeout=${SERVICE_HTTP_CONNECT_TIMEOUT:5000}
service.http.read.timeout=${SERVICE_HTTP_READ_TIMEOUT:10000}
logger.scan.interval.ms=${LOG_SCAN_INTERVAL_MS:2000}
logger.tailer.thread-count=${LOG_TAILER_THREAD_COUNT:20}
